### ISSUE TITLE
Changing the license

### ISSUE THREAD

**Issue by progre** [progre/junowen#10]
The app is currently licensed under GPLv3, but being linked from a proprietary application violates GPLv3.

Therefere, it’s necessary to update to another license, such as LGPL.

I would like to see forking projects distributed with source code, so I would like to establish a source code disclosure obligation like the LGPL.

**Comment by Aerocatia** [comment]
That is not necessary, the GPL is a distribution license, so it is not possible to break it just by using the program in some way.
What is meant by that clause is distributing this modification with the game would break the GPL, however since no one should be doing that anyway the GPL is not being broken.

**Comment by progre** [comment]
Perhaps that point is correct.
